assetPath: 'ui'
dist: '_dist'

stylesheets:
  files:
    'common.css': '{{assetPath}}/common.css'
scripts:
  files:
    'common.js': '{{assetPath}}/common.js'

tasks:
  livereload: '{{CWD}}/node_modules/clientkit-livereload'
  nunjucks: '{{CWD}}/node_modules/clientkit-nunjucks'
livereload:
  port: 8081
watcher:
  files:
    '{{dist}}/*': 'livereload'
    '{{assetPath}}/*.njk': 'nunjucks'
nunjucks:
  files:
    '{{dist}}/index.html': 
      input: 'ui/home.njk'
      type: 'compile'
